name: Docker Build and Publish

on:
#   workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Get version from package.json
      id: get_version
      run: echo "::set-output name=version::$(node -p -e "require('./package.json').version")"

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: mazurovsasha/project:${{ steps.get_version.outputs.version }}

    - name: Checkout values.yaml
      uses: actions/checkout@v2
      with:
        repository: Mazurovsasha/project-helm
        path: ./temp
        token: ${{ secrets.PROJECT_TOKEN }}

    - name: Update values.yaml
      run: |
        sed -i 's/tag:.*/tag: ${{ steps.get_version.outputs.version }}/g' ./temp/project/values.yaml
        cat ./temp/project/values.yaml
      
    - name: Commit and push changes to values.yaml
      run: |
        git config --local user.email "mazurovsasha@gmail.com"
        git config --local user.name "Alexsandr Mazurov"
        git add --all
        # git status
        # git commit -m "Update values.yaml v${{ steps.get_version.outputs.version }}"
        # git push -u origin master

    - name: Push changes
      uses: actions-go/push@v1
      with:
      #   # Override the existing remote branch if it already exist
      #   force: # optional
      #   # The email that will appear in commits when changes needs to be committed
      #   author-email: # optional, default is actions-go@users.noreply.github.com
      #   # The name that will appear in commits when changes needs to be committed
      #   author-name: # optional, default is ActionsGo Bot
      #   # Instructs to create a commit with changed files
      #   create-commit: # optional, default is true
      #   # A coma separated list of files to add to commit in addition to already staged ones. If not provided, all tracked files are committed.
      #   commit-files: # optional
      #   # The commit message used when changes needs to be committed
      #   commit-message: 
      #   # The name of the local reference to push.
      #   ref: # optional, default is ${{ github.ref }}
      #   # The name of the remote on which to push the changes. Defaults to the tracked remote
      #   remote: # optional, default is origin
      #   # The name of the remote reference to pushto. Defaults to the tracked remote branch.
      #   remote-ref: # optional, default is ${{ github.ref }}
      #   # Fail the action in case there is nothing to do.
      #   fail-if-empty: # optional
      #   # Auth token used to fetch the repository. The token is stored in the local git config, which enables your scripts to run authenticated git commands. The post-job step removes the token from the git config. [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)

        token: ${{ secrets.PROJECT_TOKEN }}
      