name: Docker Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Get version from package.json
      id: get_version
      run: echo "::set-output name=version::$(node -p -e "require('./package.json').version")"

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: mazurovsasha/project:${{ steps.get_version.outputs.version }}

    - name: Checkout values.yaml
      uses: actions/checkout@v2
      with:
        repository: Mazurovsasha/project-helm
        path: .

    - name: Update values.yaml
      run: |
        sed -i 's/taggg:.*/taggg: "${{ steps.get_version.outputs.version }}"/g' ./project/values.yaml

    - name: Execute helm lint
      run: |
        helm lint ./project
        if [ $? -eq 0 ]; then
          echo "Helm lint passed successfully"
          echo "SLACK_COLOR=good" >> $GITHUB_ENV
          echo "SLACK_MESSAGE=Helm lint passed successfully :white_check_mark:" >> $GITHUB_ENV
        else
          echo "Helm lint failed"
          echo "SLACK_COLOR=danger" >> $GITHUB_ENV
          echo "SLACK_MESSAGE=Helm lint failed :x:" >> $GITHUB_ENV
        fi

    - name: Set up SSH keys
      run: |
        sudo apt-get install -y openssh-client
        mkdir -p ~/.ssh/
        echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
        cat ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Commit and push changes to values.yaml
      run: |
        git config --global user.email "mazurovsasha@gmail.com"
        git config --global user.name "Alexsandr Mazurov"
        git add .
        git commit -m "Update values.yaml v${{ steps.get_version.outputs.version }}"
        git remote rm origin
        git remote add origin git@github.com:Mazurovsasha/project-helm.git
        git push -u origin master

    - name: Slack Notification Build and push Docker image
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: 'project_slack'
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#FF00FF'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'New Docker image with tag: ${{ steps.get_version.outputs.version }} :rocket:'
        SLACK_TITLE: Post Title
        SLACK_USERNAME: rtCamp
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
       status: ${{ job.status }}

    - name: Slack Notification helm lint
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: 'project_slack'
        SLACK_COLOR: ${{ env.SLACK_COLOR }}
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: '${{ env.SLACK_MESSAGE }}'
        SLACK_TITLE: Post Title
        SLACK_USERNAME: rtCamp
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
       status: ${{ job.status }}