name: Docker Build and Publish

on:
  # workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Get version from package.json
      id: get_version
      run: echo "::set-output name=version::$(node -p -e "require('./package.json').version")"

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: mazurovsasha/project:${{ steps.get_version.outputs.version }}

    - name: Checkout values.yaml
      uses: actions/checkout@v2
      with:
        repository: Mazurovsasha/project-helm
        path: .

    - name: Update values.yaml
      run: |
        sed -i 's/tag:.*/tag: ${{ steps.get_version.outputs.version }}/g' ./project/values.yaml

    - name: Set up SSH keys
      run: |
        sudo apt-get install -y openssh-client
        mkdir -p ~/.ssh/
        echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
        cat ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    # - name: Configure Git Credential Manager
    #   run: |
    #     wget https://github.com/git-ecosystem/git-credential-manager/releases/download/v2.4.1/gcm-linux_amd64.2.4.1.deb
    #     sudo dpkg -i ./gcm-linux_amd64.2.4.1.deb
    #     git config --global credential.helper 'store --file $HOME/.my-credentials'
                  # cd /home/runner/work/project/project/project/

    # - name: Authenticate with Git Credential Manager
    #   run: echo "${{ secrets.PROJECT_TOKEN }}" | git credential-manager install

    - name: Commit and push changes to values.yaml
      run: |
        git config --global user.email "mazurovsasha@gmail.com"
        git config --global user.name "{{ secrets.NAME }}"
        git config credential.username "{{ secrets.NAME }}"
        git add .
        git commit -m "Update values.yaml v${{ steps.get_version.outputs.version }}"
        git remote rm origin
        git remote add origin git@github.com:Mazurovsasha/project.git
        git push -u origin master