name: Docker Build and Publish

on:
  # workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Get version from package.json
      id: get_version
      run: echo "::set-output name=version::$(node -p -e "require('./package.json').version")"

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: mazurovsasha/project:${{ steps.get_version.outputs.version }}

    - name: Checkout values.yaml
      uses: actions/checkout@v2
      with:
        repository: Mazurovsasha/project-helm
        path: .

    - name: Update values.yaml
      run: |
        sed -i 's/tag:.*/tag: ${{ steps.get_version.outputs.version }}/g' ./project/values.yaml

    - name: Commit and push changes to values.yaml
      run: |
        # cd /home/runner/work/project/project/project/
        git config --global user.email "mazurovsasha@gmail.com"
        git config --global user.name "{{ secrets.NAME }}"
        git config credential.username "{{ secrets.NAME }}"
        git config credential.helper "store --file=.git/credentials"
        git add .
        git commit -m "Update values.yaml v${{ steps.get_version.outputs.version }}"
        git remote add origin https://"Mazurovsasha":"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"@github.com/Mazurovsasha/project-helm.git
        git push
        # git remote rm origin
        # git remote add origin https://github.com/Mazurovsasha/project-helm.git
        # git remote set-url origin https://x-access-token:${{ secrets.PROJECT_TOKEN }}@github.com/Mazurovsasha/project-helm.git
        # git push --force --set-upstream helm-origin master "${GH_TOKEN}"
        # git push --set-upstream origin master 


    # - name: Git Commit Push Action
    #   uses: GuillaumeFalourd/git-commit-push@v1.3
    #   with:
    #     # Committer's email address
    #     email: mazurovsasha@gmail.com
    #     # Committer's username
    #     name: Alexsandr Mazurov
    #     # Commit message
    #     commit_message: Update values.yaml v${{ steps.get_version.outputs.version }}
    #     # Branch to push the changes back to
    #     target_branch: master
    #     # Files to add separated by space
    #     files: .
    #     # Repository url to push the code to
    #     remote_repository: "https://github.com/Mazurovsasha/project-helm.git"
    #     # Token used to push the code
    #     access_token: ${{ secrets.PROJECT_TOKEN }}


