name: Docker test

on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Build and deploy Docker image
      run: |
        docker build -t test-image .
        docker run -d --name test-container test-image

    - name: Test by requesting data from imager
      run: |
        docker exec test-container curl http://localhost
              
    - name: Test if image has not root access inside
      run: |
        docker exec test-container id 