name: Kubeval Validation

on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Install kubeval
      run: |
        curl -LO https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
        tar xf kubeval-linux-amd64.tar.gz
        sudo cp kubeval /usr/local/bin

    - name: Checkout values.yaml
      uses: actions/checkout@v2
      with:
        repository: Mazurovsasha/project-helm
        path: .
    
    - name: Kubeval Validation
      id: kubeval
      run: |
        kubeval --strict -d ./project/templates >> report.txt || true
        output="$(cat report.txt)"
        echo "::set-output name=output::$output"

    - name: Echo
      run: |
        echo '${{ steps.kubeval.outputs.output }}'

    - name: Upload validation report
      uses: actions/upload-artifact@v4
      id: artifact-upload-step
      with:
        name: validation-report
        path: report.txt

    - name: Output artifact URL
      run:  echo 'Artifact URL is ${{ steps.artifact-upload-step.outputs.artifact-id }}'

    # - name: Download validation report artifact
    #   uses: actions/download-artifact@v2
    #   with:
    #     name: validation-report
    #     path: downloaded-artifacts

    - name: Slack Notification Kubeval Validation
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: 'project_slack'
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: |
          Результат Kubeval Validation:
          ${{ steps.kubeval.outputs.output }}
           [Ссылка на отчет о валидации](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }})
        SLACK_TITLE: Kubeval Validation
        SLACK_USERNAME: rtCamp
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        status: ${{ job.status }}